spring.application.name=backend
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://fallout-db.cducaea68apg.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sweetheart1!9999
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true